# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Thu, 27 May 2021 13:06:56 +0000
*	@ALL	1
*	@user	1
milestones	@ALL	0
