<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: admin
 * Date: Wed, 26 Jan 2022 12:37:26 +0100
 */

$conf['title'] = 'Conzept guide';
$conf['start'] = 'home';
$conf['template'] = 'readthedokus';
$conf['license'] = 'cc-by-sa';
$conf['basedir'] = '/guide/';
$conf['baseurl'] = 'https://conze.pt';
$conf['maxtoclevel'] = '5';
$conf['maxseclevel'] = '5';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['htmlok'] = 1;
$conf['target']['interwiki'] = '_blank';
$conf['target']['extern'] = '_blank';
$conf['target']['media'] = '_blank';
$conf['userewrite'] = '1';
$conf['plugin']['fontface']['technique'] = 'google';
$conf['plugin']['fontface']['fontFile'] = 'Hind';
$conf['plugin']['fontface']['fontName'] = 'Hind';
$conf['plugin']['fontface']['genericFamily'] = 'sans-serif';
$conf['plugin']['fontface']['fontFile2'] = 'Hind';
