# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Thu, 27 May 2021 13:06:56 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

admin:$1$4fd0ad31$.cId7p1uxI4a.RcrH81On0:Admin:info@conze.pt:admin,user
