# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Thu, 27 May 2021 13:06:56 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

admin:$2y$10$Cpg5rG1NdmsvZ4IxiL5cue6F.RW9Osvp4cyJwQtUeZLvfEsDRC7PK:Admin:info@conze.pt:admin,user
