# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Thu, 27 May 2021 13:06:56 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated
admin:$2y$10$8RXpR8ufxrSOTQJKCT8cduyJVqhQpABZT44.oX3iP/WMTgQNU3mou:Admin:info@conze.pt:admin,user
