const CONZEPT_VERSION = "0.51.474";
const CONZEPT_LOCALES = "ar, ceb, de, en, es, fr, hi, it, ja, nl, pt, ru, sv, zh, uk, bn, id, ur, mr, te, tr, ta, ko, vi, ha, fa, sw, da, no, bn, ca, sr, fi, hu, cs, hr";
const CONZEPT_EMAIL = "jama@conze.pt";
const CONZEPT_WEB_BASE = "";
const CONZEPT_CORS_PROXY_WHITELIST = "upload.wikimedia.org, commons.wikimedia.org, commons.m.wikimedia.org, maps.wikimedia.org";
const CONZEPT_HOSTNAME = "conze.pt";
const CONZEPT_AI_TUTORS = "auto-select, default, advisor-related-websites, advisor-topic-differences, advisor-related-topics, advisor-topic-commonality, advisor-topic-implications, advisor-related-books, advisor-related-science-articles, language-helper, examinator, teacher, historian, scientist, philosopher, mathematician, chemist, economist, politician, art-history, artist, travel-guide, statistician, nutritionist, psychologist, legislator, theologian, poet, storyteller, biologist, doctor, investor, lifecoach, entrepreneur, farmer, ecologist, military-expert, financial-expert, engineer, professor, demographer, social-scientist, linguist";
const CONZEPT_INDICATORS_VERSION = "0.225";
const CONZEPT_FONT = "Hind";
